### ISSUE TITLE
get_type_prob possible bug

### ISSUE THREAD

**Issue by cristian-nicolescu** [integrated-inferences/CausalQueries#268] opened 2023-09-19 20:35 UTC
model <- make_model("X  -> Y")
model <- update_model(model, data = data.frame(X = c(1, 0 ,1), Y = c(0, 0, 1)))
get_type_prob(model, parameters = model$posterior_distribution[1, ])

Used to work before, error is now:
 Error in min(parameters_df$param_value) : 
  invalid 'type' (list) of argument
  
Happens as soon as you update. Also if you use a perfectly normal vector in parameters =, which is rather unexpected.

**Comment by till-tietz** [comment] 2023-09-19 21:45
@cristian-nicolescu this error is triggered by the clean_param_vector call in get_type_prob and is a result of passing a data.frame/row vector to the parameters argument (vectors should work fine in the current version on master)

doing the following works 
```
model <- make_model("X -> Y")
model <- update_model(model, data = data.frame(X = c(1, 0 ,1), Y = c(0, 0, 1)))
get_type_prob(model, parameters = as.vector(t(model$posterior_distribution[1, ])))
```

We can add a more informative error message or internally force transformation to vectors

**Comment by till-tietz** [comment] 2023-09-19 21:55
Infact just this works 

```
get_type_prob(model, parameters = t(model$posterior_distribution[1, ]))
```

as clean_param_vector alread calls as.vector when assigning new parameters to parameters_df. The issue is as.vector converting row vectors to list as R uses column major formats by default

**Comment by cristian-nicolescu** [comment] 2023-09-20 12:28
Thanks!! Yes I was a bit thrown off because I could have sworn that it used
to work in version 0.1.0!

**Comment by till-tietz** [comment] 2023-09-20 12:30
I'm adding a check for class(vector) and a more helpful error message. Will close the issue after that push unless there are further related problems on your end.

**Comment by till-tietz** [comment] 2023-09-20 14:29
```
model <- make_model("X -> Y")
model <- update_model(model, data = data.frame(X = c(1, 0 ,1), Y = c(0, 0, 1)))
get_type_prob(model, parameters = model$posterior_distribution[1, ])
```
now returns 

```
Error in clean_param_vector(model, parameters) : 
  parameters should be a vector
```

**Closed by till-tietz** 2023-09-20 14:29 UTC
Labels: enhancement, medium priority, errors + warnings

**Comment by cristian-nicolescu** [comment] 2023-09-20 15:27
Looks great, thanks!
